#+title: Cash Flow from Financial Statements
#+author: Matt Brigida, Ph.D.
#+SETUPFILE: https://fniessen.github.io/org-html-themes/setup/theme-readtheorg.setup

To value an asset we need the cash flows generated by that asset, and we use financial statements to calculate cash flow.  In this section we'll discuss (1) a general overview of financial statements so you'll know where to look for a given piece of information and (2) how to extract cash flows from financial statements.

* The Balance Sheet

The /balance sheet/ is a summary of how a firm financed their assets at one point in time.  [[https://www.5minutefinance.org/concepts/the-balance-sheet-identity][This is often written as the balance sheet identity, which shows Assets are /defined/ to be the sum of liabilities and stockholders' equity (see the link for the difference between an equation and an identity).]] 

$$Assets \equiv Liabilities + Stockholders'\ Equity$$

On the left hand side we have the assets of the firm, recorded at the purchase cost of the asset.  On the right-hand side we have the value of the liabilities (debt) issued and the /book/ value of the firm's common stock.  

By looking at the change in certain accounts, we can identify corporate actions such as stock and bond issuance, or retained earnings.  For example, say the YoY (year over year) change in long-term debt on the balance sheet is $100 million.  This means the company issued (sold) $100 million in debt over the year.

** Market vs Book Values

The asset values in the audited FASB (Financial Accounting Standard Board) balance sheet are /book values/ which is the cost of the asset.  In finance, we are interested in market values rather than book values, so it is important to keep the distinction between /market/ and /book/ values in mind.  For example, since equity on the balance sheet is defined to be the book value of asset minus liabilities (which is a book value), it is generally is substantially different from the market value of equity.

** Liquidity

Liquidity is:

#+BEGIN_QUOTE
The ease with which you can sell an asset for cash, while not reducing its value by much.
#+END_QUOTE

Assets on the balance sheet are listed in order of decreasing liquidity---the most liquid assets are on the top.  

** Financial Leverage 

/Financial Leverage/ refers to the amount of debt in a firm's capital structure.  More debt magnifies returns, and hence 'leverage' refers to using debt to making returns larger as if by a sort of mechanical advantage.  For example:

#+BEGIN_QUOTE
Say you have $100,000 and each house costs $100,000.  Also all houses are expected to increase by 1% per year. If you buy one house (100% equity), and houses increase by 1%, you have a 1% return on equity over the year.

If instead, you buy 100 houses, putting down $1000 in equity on each house (1% equity), and house prices increase by 1%, then you have a 100% return on equity. Leverage has magnified your gain.

Of course, if house prices had declined by 1% you would have lost $1000 in the 100% equity case, and $100,000 in the 1% equity case.
#+END_QUOTE

The balance sheet affords the (book) value of leverage.  Because this is a book value number, it should be compared with other, similar, firms' leverage values.  

In the U.K. /Leverage/ is called as /Gearing/.  Both imply the 'mechanical advantage' available through debt.





* The Income Statement

The income statement measures a firm’s performance over some period of time.

- If the balance sheet is a snapshot (picture) then the income statement is like a video recording.

- Roughly, the income statement looks like: $Revenue - Expenses = Income$

- Accounting standards (GAAP) require matching revenues with expenses. This means when you earn income may not be when you receive cash—a sale on credit will be income even though you may not receive the cash for some time.

- Noncash Items: To match revenues with expenses noncash items are added to the income statement. For example, the purchase of a truck will be depreciated which means the expense of a truck on the income statement isn’t incurred when you pay for the truck, but rather the expense is realized over the truck’s life (while the truck is earning revenue).

- Variable vs Fixed Costs: no distinction is made on the income statement between variable and fixed costs.


*  The Statement of Cash Flows

The cash flow statement is a combination of balance sheet and income statement.

- The statement captures how the changes in both balance sheet and income affects cash and cash equivalents.

- There are three portions to the cash flow statement: Operating, Investing, and Financing activities.

- Cash flow on the accounting statement is not equivalent with financial cash flow. Among the causes of the disparity is the treatment of interest expense, which the accounting treats as an operating expense. For the financial analyst, interest is purely a financing (and not operating) activity.

* Cash Flow

** Operating Cash Flow

$$OCF = EBIT + Depreciation - Taxes$$

*** A note on interest expense

Interest is a cash expense, however we will not include it in any of our OCF calculations.

** Cash Flow from Assets

